import Head from 'next/head'
import SideBar from '@/app/TutorDashboard/SideBar'
import React, { FC, ReactElement, useState } from 'react'

type DashboardLayoutProps = {
  children: ReactElement
}

const DashboardLayout: FC<DashboardLayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>Tutor-Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='flex bg-white'>
        <div className={'md:w-52 w-14 bg-[#121212] h-screen overflow-y-auto'}>
          <SideBar />
        </div>
        <div className='w-full md:flex-1 pt-[24px] px-[18px] h-screen overflow-y-auto'>
          {children}
        </div>
      </div>
    </>
  )
}

export default DashboardLayout
