import Head from 'next/head'
import React, { FC, ReactElement } from 'react'
import TutorprofileNavbar from '../../components/navbar'

type TutorLayoutProps = {
  children: ReactElement
}

const TutorLayout: FC<TutorLayoutProps> = ({ children }) => {
  return (
    <>
      <Head>
        <title>TutorProfile</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <TutorprofileNavbar />
      {children}
    </>
  )
}

export default TutorLayout
